import os
import json
import pandas as pd

from config import OUTPUT_DIR, QUERIES_LOG, log
# 5. Output 
def to_df(results):
    df = pd.DataFrame(results) if results else pd.DataFrame()
    for c in df.select_dtypes(include="datetime64[ns]").columns:
        df[c] = df[c].dt.strftime("%d-%m-%Y")
    return df

def show(results):
    df = to_df(results)
    print("\n" + (df.to_string(index=False) if not df.empty else "No results found.") + "\n")

def save(results, filename):
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    path = f"{OUTPUT_DIR}/{filename}"
    to_df(results).to_csv(path, index=False)
    log.info("Saved → %s", path)

def log_query(question, query):
    with open(QUERIES_LOG, "a") as f:

        mongo_query = (
            f'db.collection.find({json.dumps(query.get("filter", {}))})'
        )

        if query.get("sort"):
            mongo_query += f'.sort({json.dumps(query["sort"])})'

        f.write(f"Question: {question}\n")
        f.write(f"Query generated by Model - {mongo_query}\n")
        f.write("\n")

def validate_columns(question, df):
    if not any(c.lower() in question.lower() for c in df.columns):
        log.warning("No column name detected. Valid columns: %s", list(df.columns))
